paths:
  data:
    main: ./data
    raw: ${paths.data.main}/raw
    interim: ${paths.data.main}/interim
    processed: ${paths.data.main}/processed
  
files:
  raw_dataset: netztest-opendata.csv
  processed_dataset: netztest-opendata-processed.csv

logging:
  level: DEBUG
  fmt: '[%(levelname)s %(asctime)s %(module)s] %(message)s'
  date_fmt: '%Y-%m-%d %H:%M:%S'

filters:
# Which records to keep
  cat_technology:
    equals:
      - 3G
      - 4G
      - 5G

inputs:
# Which columns from the raw dataset should be kept
  - lat
  - long
  - download_mbit
  - upload_mbit
  - ping_ms
  #- lte_rsrp
  - signal_strength
  - platform
  - network_name

target:
 cat_technology

