channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - flake8
  - pytest
  - scikit-learn
  - lightgbm
  - ipykernel
  - pandas-profiling
  - hydra-core
  - pip
  #- pip:
  #    - antlr4-python3-runtime==4.8
