channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - pandas
  - numpy
  - flake8
  - pytest
  - scikit-learn
  - lightgbm
  - ipykernel
  - pandas-profiling
  - omegaconf=2.0.0  # avoid antlr warning in vs code
  - pip
  - pip:
      - antlr4-python3-runtime==4.8
      - -e .
